
name: Delete Contentful Environment on merge
on: 
  pull_request:
    types: [closed]
  
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
    
      - name: Delete Contentful Environment
        id: deletion
        # if: github.event.pull_request.merged
        # uses: ./utils/delete-contentful-environment
        run: './utils/delete-contentful-env'
        env:
          SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          MANAGEMENT_API_KEY: ${{ secrets.CONTENTFUL_MANAGEMENT_API_KEY }}
      - name: Comment Contentful Info
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            Contentful Environment Deleted Successfully :sparkles:
            
            **Environment Name**: _${{ steps.deletion.outputs.environment_name }}_