
name: Test Migration And Deploy Contentful

on:
  pull_request:
    branches: [ master ]
    paths:
      - "migrations/**"
      - ".github/workflows/pr.yml"
  push:
    branches: [ master ]
    paths:
      - "migrations/**"
      - ".github/workflows/pr.yml"

jobs:

  deploy_contentful:
    name: Deploy Contentful Sandbox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy Contentful
        id: migration
        uses: contentful/contentful-action@main
        with:
          delete_feature: false
          set_alias: true
          master_pattern: "prod-[DD].[MM].[YYYY]-[hh][mm][ss]"
          feature_pattern: "sandbox-[branch]"
          SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          MANAGEMENT_API_KEY: ${{ secrets.CONTENTFUL_MANAGEMENT_API_KEY }}
          MIGRATIONS_DIR: test-migrations
          VERSION_FIELD: version
          VERSION_CONTENT_TYPE: versionTracking

      - name: Comment Contentful Info
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            Contentful Environment Created and Migrated Successfully :sparkles:
            
            **Environment Name**: _${{ steps.migration.outputs.environment_name }}_

            Click [here][1] to go to new environment
            
            [1]: ${{steps.migration.outputs.environment_url}}