
name: Test Migration And Deploy Contentful

on:
  pull_request:
    branches: [ master ]
    paths:
      - "migrations/**"
      - ".github/workflows/pr.yml"
  push:
    branches: [ master ]
    paths:
      - "migrations/**"
      - ".github/workflows/pr.yml"

jobs:
  deploy_contentful:
    name: Deploy Contentful Sandbox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy Contentful
        id: migration
        uses: contentful/contentful-action@main
        env:
          SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          MANAGEMENT_API_KEY: ${{ secrets.CONTENTFUL_MANAGEMENT_API_KEY }}
          MIGRATIONS_DIR: 'migrations'
          # set_alias: true
          
      - name: Comment Contentful Info
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            Contentful Environment Created and Migrated Successfully :sparkles:
            
            **Environment Name**: _${{ steps.migration.outputs.environment_name }}_

            Click [here][1] to go to new environment
            
            [1]: ${{steps.migration.outputs.environment_url}}